# Generated by Django 4.2.1 on 2023-05-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
