# Generated by Django 4.2.1 on 2023-05-14 09:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_quizanswer_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='question_name',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_status',
        ),
        migrations.AddField(
            model_name='quiz',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_name',
            field=models.CharField(default='newquiz', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizapp.quizstatus'),
        ),
        migrations.AlterField(
            model_name='quizstatus',
            name='status_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=1000)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_quiz', to='quizapp.quiz')),
            ],
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answer', to='quizapp.quizquestion'),
        ),
    ]
