# Generated by Django 4.2.1 on 2023-05-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_remove_quiz_question_name_remove_quiz_quiz_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
